# Generated by Django 6.0.1 on 2026-02-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_views_counter"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="new_item",
            field=models.BooleanField(
                default=False,
                help_text="Введите признак новинки продукта",
                verbose_name="Признак новинки",
            ),
        ),
    ]
